"""Add column photo for students

Revision ID: 78935beba0f1
Revises: da89e4b73392
Create Date: 2025-06-25 21:59:14.568798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78935beba0f1'
down_revision: Union[str, None] = 'da89e4b73392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('photo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'photo')
    # ### end Alembic commands ###
